// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDD7fUs6hQ0wmc4DyDlSXEnqJVgb-8d92w',
    appId: '1:436999151575:web:5998a5ea066c09d1c33592',
    messagingSenderId: '436999151575',
    projectId: 'zolza-hairstyles',
    authDomain: 'zolza-hairstyles.firebaseapp.com',
    storageBucket: 'zolza-hairstyles.appspot.com',
    measurementId: 'G-JFC9R9LRXY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgPkVDeZtWnDgAcXMTC8_BLXyrp58L9xg',
    appId: '1:436999151575:android:6845e907727ef20dc33592',
    messagingSenderId: '436999151575',
    projectId: 'zolza-hairstyles',
    storageBucket: 'zolza-hairstyles.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARof-2Cc_t7tnbrCxWBd7jzkGOiFL6Ipg',
    appId: '1:436999151575:ios:a8c4d321b206e0bac33592',
    messagingSenderId: '436999151575',
    projectId: 'zolza-hairstyles',
    storageBucket: 'zolza-hairstyles.appspot.com',
    androidClientId: '436999151575-f8u39s03als9j6ps38pei525qb1ko5rp.apps.googleusercontent.com',
    iosClientId: '436999151575-ijhs4to39nantl2ngalljlc95q582rjd.apps.googleusercontent.com',
    iosBundleId: 'pl.zolzahairstyles.app',
  );
}
